name: Docker Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker buildx build --build-arg VERSION=${{ env.VERSION }} \
          --platform linux/amd64,linux/arm64 \
          --push -t damongolding/immich-kiosk:${{ env.VERSION }} \
          -t damongolding/immich-kiosk:latest .

      - name: Construct release URL
        run: |
          REPO_OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          RELEASE_URL="https://github.com/$REPO_OWNER/$REPO_NAME/releases/tag/v${{ env.VERSION }}"
          echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Immich Kiosk ${{ env.VERSION }} has been released! Check it out: ${{ env.RELEASE_URL }}"
